name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Quando um push é feito na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Git
        run: git config --global user.name "matheusthimoty" && git config --global user.email "matheusthimoty@outlook.com"

      - name: Instalar dependências
        run: npm install  

      - name: Build do projeto
        run: echo "Este passo pode ser removido caso não tenha processo de build, pois seu projeto é puro HTML"

      - name: Configurar branch gh-pages
        run: |
          git remote set-url origin https://github.com/matheusthimoty/seu-repositorio.git
          git fetch
          git checkout --orphan gh-pages  # Cria uma nova branch sem histórico de commit

      - name: Copiar arquivos para a branch gh-pages
        run: |
          cp -r * .  # Copia todos os arquivos da branch main para a nova branch gh-pages
          git add .
          git commit -m "Deploy para GitHub Pages"
          git push origin gh-pages --force  # Push da nova branch gh-pages
